# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Subject.create(name: "Discrete Mathematics", 				   code: "MA-2003", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Data Structures and Algorithms", 		   code: "CS-2001", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Mathematics-3",						   code: "MA-2001", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Digital Electronic Circuits", 		   code: "EC-2009", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Environmental Science", 				   code: "CH-2001", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Database Management Systems", 		   code: "CS-2004", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Operating Systems", 					   code: "CS-2002", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Principle of Digital Communication", 	   code: "EC-2004", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Mathematics-4", 						   code: "MA-2002", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Design and Analysis of Algorithms", 	   code: "CS-3001", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Formal Languages and Automata Theory",   code: "CS-3003", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Computer Organization and Organization", code: "CS-3005", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Compiler Design", 					   code: "CS-3002", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "High Performance Computer Architecture", code: "CS-3006", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Computer Graphics", 					   code: "CS-3004", branch: "COMPUTER SCIENCE & ENGINEERING")
Subject.create(name: "Artificial Intelligence", 			   code: "CS-4001", branch: "COMPUTER SCIENCE & ENGINEERING")


Subject.create(name: "Object Oriented Programming", 	 code: "IT-2001", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Programming Tools and Techniques", code: "IT-2002", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Software Engineering", 			 code: "IT-3003", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Computer Networks", 				 code: "IT-3001", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Object Oriented System Design", 	 code: "IT-3004", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Data Analytics", 					 code: "IT-3002", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Mobile computing", 				 code: "IT-3006", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Data Mining", 					 code: "IT-4003", branch: "INFORMATION TECHNOLOGY")
Subject.create(name: "Enterprise Resource Planning", 	 code: "IT-4001", branch: "INFORMATION TECHNOLOGY")

Subject.create(name: "Mathematics-3", 			                        code: "MA-2001", branch: "CIVIL ENGINEERING")
Subject.create(name: "Fluid Mechanics-1", 			                    code: "CE-2001", branch: "CIVIL ENGINEERING")
Subject.create(name: "Solid Mechanics-1", 			                    code: "CE-2003", branch: "CIVIL ENGINEERING")
Subject.create(name: "Surveying", 			                            code: "CE-2005", branch: "CIVIL ENGINEERING")
Subject.create(name: "CIVIL ENGINEERINGEngg. Materials & Construction", code: "CE-2007", branch: "CIVIL ENGINEERING")
Subject.create(name: "Environmental Engineering-1",                     code: "CE-2009", branch: "CIVIL ENGINEERING")
Subject.create(name: "Numerical Methods", 			                    code: "MA-2004", branch: "CIVIL ENGINEERING")
Subject.create(name: "Fluid Mechanics-2", 			                    code: "CE-2002", branch: "CIVIL ENGINEERING")
Subject.create(name: "Structural Analysis-1", 			                code: "CE-2004", branch: "CIVIL ENGINEERING")
Subject.create(name: "Transportation Engineering-1",                    code: "CE-2006", branch: "CIVIL ENGINEERING")
Subject.create(name: "Advanced Surveying", 			                    code: "CE-2008", branch: "CIVIL ENGINEERING")
Subject.create(name: "Design Of Concrete Structure-1",                  code: "CE-2012", branch: "CIVIL ENGINEERING")
Subject.create(name: "Structural Analysis-2", 			                code: "CE-3001", branch: "CIVIL ENGINEERING")
Subject.create(name: "Water Resources Engineering-1",                   code: "CE-3003", branch: "CIVIL ENGINEERING")
Subject.create(name: "Geotechnical Engineering-1", 			            code: "CE-3004", branch: "CIVIL ENGINEERING")
Subject.create(name: "Design Of Steel Structure",                       code: "CE-3007", branch: "CIVIL ENGINEERING")
Subject.create(name: "Engineering Economics",                           code: "HS-2002", branch: "CIVIL ENGINEERING")
Subject.create(name: "Water Resources Engineering-2",                   code: "CE-3002", branch: "CIVIL ENGINEERING")
Subject.create(name: "Geotechnical Engineering-2",                      code: "CE-3005", branch: "CIVIL ENGINEERING")
Subject.create(name: "Design Of Concrete Structure-2",                  code: "CE-3006", branch: "CIVIL ENGINEERING")
Subject.create(name: "Environmental Engineering-2",                     code: "CE-3008", branch: "CIVIL ENGINEERING")
Subject.create(name: "Construction Planning & Management",              code: "CE-3012", branch: "CIVIL ENGINEERING")
Subject.create(name: "Transportation Engineering-2",                    code: "CE-4001", branch: "CIVIL ENGINEERING")


Subject.create(name: "Engineering Thermodynamics",                                code: "ME-2001", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Fluid Mechanics",                                           code: "ME-2003", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Mechanics of Solids",                                       code: "ME-2005", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Material Science And Engineering",                          code: "ME-2007", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Kinematics & Kinetics Of Mechanics",                        code: "ME-2009", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Mathematics-3",                                             code: "MA-2001", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Machine Dynamics",                                          code: "ME-2002", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Heat Transfer",                                             code: "ME-2004", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Basic Manufacturing Process",                               code: "ME-2006", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Introduction To Electrical Machines And Power Electronics", code: "EE-2006", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Numerical Methods",                                         code: "MA-2004", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Environmental Science",                                     code: "CH-2001", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Fluid Dynamics & Hydraulic Machines",                       code: "ME-3001", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Internal Combustion Engines & Gas Turbines",                code: "ME-3003", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "MECHANICAL Measurements And Control ",                      code: "ME-3005", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Manufacturing Process & Design",                            code: "ME-3007", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Fundamentals Of Machine Design",                            code: "ME-3009", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Refrigetion And Air Conditioning",                          code: "ME-3002", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Metal Cutting And Cutting Tool Design",                     code: "ME-3004", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Metrology, Quality Control And Reliability",                code: "ME-3006", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Industrial Engineering And Management",                     code: "ME-3008", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Design Of Machine Elements",                                code: "ME-3012", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Advanced Manufacturing Process",                            code: "ME-4001", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Power Plant Engineering",                                   code: "ME-4003", branch: "MECHANICAL ENGINEERING")
Subject.create(name: "Industrial Automation",                                     code: "ME-4002", branch: "MECHANICAL ENGINEERING")


Subject.create(name: "Mathematics-3",                                code: "MA-2001", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Electrical Machines-1",                        code: "EE-2001", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Network Analysis",                             code: "EE-2003", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Analog Electronics",                           code: "EE-2007", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Data Structure And Java Programming",          code: "CS-2003", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Environmental Science",                        code: "CH-2001", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Mathematics-4",                                code: "MA-2002", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "ELECTRICAL Machines-2",                        code: "EE-2002", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Digital Electronics Circuits",                 code: "EC-2009", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "ELECTRICAL Measurements And Instrumentation",  code: "EE-2004", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Thermal Engineering Applications",             code: "ME-2016", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Electric Power Transmission And Distribution", code: "EE-3001", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Linear Control Theory",                        code: "EE-3003", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Power Electronics",                            code: "EE-3005", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Microprocessors And Microcontrollers",         code: "EC-3003", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Power Systems Operation And Control",          code: "EE-3002", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Electromagnetic Field",                        code: "EE-3004", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Communication Engineering",                    code: "EC-3009", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Introduction To Digital Signal Processing",    code: "EC-3008", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Electric Drives",                              code: "EE-4001", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Switch Gear And Protection",                   code: "EE-4003", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Renewable Energy Systems",                     code: "EE-4005", branch: "ELECTRICAL ENGINEERING")
Subject.create(name: "Industrial Automation And Control",            code: "EL-4001", branch: "ELECTRICAL ENGINEERING")


Subject.create(name: "Mathematics-3",                               code: "MA-2001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Analog Electronic Circuits-1",                code: "EC-2001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Signals & Systems",                           code: "EC-2003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Network Analysis",                            code: "EE-2003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Semiconductor Devices",                       code: "EC-2005", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Data Structure And Java Programming",         code: "CS-2003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Mathematics-4",                               code: "MA-2002", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Analog Electronic Circuits-2",                code: "EC-2002", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Analog Communication Techniques",             code: "EC-2006", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Measurements & Instrumentation",              code: "EC-2008", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Digital Electronic Circuits",                 code: "EC-2009", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Environmental Science",                       code: "CH-2001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Electromagnetic Theory",                      code: "EC-3001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Microprocessors And Microcontrollers",        code: "EC-3003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Control Systems",                             code: "EL-3001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Digital Communication Techniques",            code: "EC-3005", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Antenna And Wave Propagation",                code: "EC-3002", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "VLSI Design",                                 code: "EC-3004", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Digital Signal Processing",                   code: "EC-3007", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Data Communication & Networking",             code: "EC-3006", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "RF & Microwave Engineering",                  code: "EC-4001", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Wireless & Mobile Communication Engineering", code: "EC-4003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")
Subject.create(name: "Computer Organization And Operating Systems", code: "CS-4003", branch: "ELECTONICS & TELECOMMUNICATION ENGINEERING")


Subject.create(name: "Mathematics-3",                              code: "MA-2001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Analog Electronic",                          code: "EC-2007", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Network Analysis",                           code: "EE-2003", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Signals And Systems",                        code: "EC-2003", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Electrical Machines-1",                      code: "EE-2001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Data Structure And Java Programming",        code: "CS-2003", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Mathematics-4",                              code: "MA-2002", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Electrical Machines-2",                      code: "EE-2002", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Measurements & Instrumentation",             code: "EC-2008", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Digital Electronic Circuits",                code: "EC-2009", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Environmental Science",                      code: "CH-2001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Electromagnetic Theory",                     code: "EC-3001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Electric Power Transmission & Distribution", code: "EE-3001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Microprocessors And Microcontrollers",       code: "EC-3003", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Control Systems",                            code: "EL-3001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Digital Signal Processing",                  code: "EC-3007", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Communication Engineering",                  code: "EC-3009", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Power Electronics",                          code: "EE-3005", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Power System Operation And Control",         code: "EE-3002", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Electric Drives",                            code: "EE-4001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Switch Gear And Protection",                 code: "EE-4003", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Industrial Automation And Control",          code: "EL-4001", branch: "ELECTONICS & ELECTRICAL ENGINEERING")
Subject.create(name: "Data Communication And Networking",          code: "EC-3006", branch: "ELECTONICS & ELECTRICAL ENGINEERING")


Subject.create(name: "Mathematics-3",                        code: "MA-2001", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Signals And Systems",                  code: "EC-2003", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Analog Electronics",                   code: "EC-2007", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Network Analysis",                     code: "EE-2003", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Semiconductor Devices",                code: "EC-2005", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Data Structure And Java Programming",  code: "CS-2003", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Mathematics-4",                        code: "MA-2002", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Material Science",                     code: "EI-2002", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Digital Electronics Circuits",         code: "EC-2009", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Electrical And Electric Measurements", code: "EI-2004", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Electrical Machines",                  code: "EE-2008", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Environmental Science",                code: "CH-2001", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Microprocessors And Microcontrollers", code: "EC-3003", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Instrumentation-1",                    code: "EI-3001", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Communication Engineering",            code: "EC-3009", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Control Systems",                      code: "EL-3001", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Thermodynamics And Fluid Mechanics",   code: "ME-3013", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Digital Signal Processing",            code: "EC-3007", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Process Control-1",                    code: "EI-3004", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Instrumentation-2",                    code: "EI-3002", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Power Electronics",                    code: "EE-3005", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "VLSI Design",                          code: "EC-3004", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Analytical Instrumentation",           code: "EI-4001", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")
Subject.create(name: "Process Control-2",                    code: "EI-4003", branch: "ELECTONICS & INSTRUMENTATION ENGINEERING")


Subject.create(name: "Mathematics-1",              code: "MA-1001", branch: "FIRST YEAR")
Subject.create(name: "Physics-1",                  code: "PH-1001", branch: "FIRST YEAR")
Subject.create(name: "Chemistry-1",                code: "CH-1001", branch: "FIRST YEAR")
Subject.create(name: "Engineering Mechanics",      code: "ME-1001", branch: "FIRST YEAR")
Subject.create(name: "Electrical Science",         code: "EE-1001", branch: "FIRST YEAR")
Subject.create(name: "Mathematics-2",              code: "MA-1002", branch: "FIRST YEAR")
Subject.create(name: "Physics-2",                  code: "PH-1002", branch: "FIRST YEAR")
Subject.create(name: "Programming In C",           code: "CS-1001", branch: "FIRST YEAR")
Subject.create(name: "Basic Electronics",          code: "EC-1001", branch: "FIRST YEAR")
Subject.create(name: "Professional Communication", code: "HS-1001", branch: "FIRST YEAR")

puts "Seeding Complete"